In [1]:
import os
from dataloading import get_yolox_datadir
from pycocotools.coco import COCO
import numpy as np
import cv2

In [2]:
data_dir = os.path.join(get_yolox_datadir(), "Jerry")

In [3]:
data_dir

'/home/administrator/deeplearning/code/Gayhub/detection/MOT/Jerry/ByteTrack/datasets/Jerry'

In [4]:
json_file="train_half.json"
name="train"
img_size=(608, 1088)
preproc=None

In [5]:
def load_anno_from_ids(id_):
    im_ann = coco.loadImgs(id_)[0]
    width = im_ann["width"]
    height = im_ann["height"]
    frame_id = im_ann["frame_id"]
    video_id = im_ann["video_id"]
    anno_ids = coco.getAnnIds(imgIds=[int(id_)], iscrowd=False)
    annotations = coco.loadAnns(anno_ids)
    objs = []
    for obj in annotations:
        x1 = obj["bbox"][0]
        y1 = obj["bbox"][1]
        x2 = x1 + obj["bbox"][2]
        y2 = y1 + obj["bbox"][3]
        if obj["area"] > 0 and x2 >= x1 and y2 >= y1:
            obj["clean_bbox"] = [x1, y1, x2, y2]
            objs.append(obj)

    num_objs = len(objs)

    res = np.zeros((num_objs, 6))

    for ix, obj in enumerate(objs):
        cls = class_ids.index(obj["category_id"])
        res[ix, 0:4] = obj["clean_bbox"]
        res[ix, 4] = cls
        res[ix, 5] = obj["track_id"]

    file_name = im_ann["file_name"] if "file_name" in im_ann else "{:012}".format(id_) + ".jpg"
    img_info = (height, width, frame_id, video_id, file_name)

    del im_ann, annotations

    return (res, img_info, file_name)

In [6]:
def _load_coco_annotations():
    return [load_anno_from_ids(_ids) for _ids in ids]

In [7]:
coco = COCO(os.path.join(data_dir, "annotations", json_file))
ids = coco.getImgIds()
class_ids = sorted(coco.getCatIds())
cats = coco.loadCats(coco.getCatIds())
_classes = tuple([c["name"] for c in cats])
annotations = _load_coco_annotations()
# self.name = name
# self.img_size = img_size
# self.preproc = preproc

loading annotations into memory...
Done (t=0.05s)
creating index...
index created!


In [8]:
annotations = _load_coco_annotations()

In [9]:
annotations

[(array([[1.700e+01, 5.200e+02, 6.500e+01, 5.800e+02, 0.000e+00, 1.000e+00],
         [5.760e+02, 4.960e+02, 5.950e+02, 5.560e+02, 0.000e+00, 2.000e+00],
         [5.910e+02, 4.960e+02, 6.230e+02, 5.550e+02, 0.000e+00, 3.000e+00],
         [6.520e+02, 4.950e+02, 6.780e+02, 5.540e+02, 0.000e+00, 4.000e+00],
         [6.970e+02, 4.900e+02, 7.350e+02, 5.570e+02, 0.000e+00, 5.000e+00],
         [7.760e+02, 4.950e+02, 8.130e+02, 5.550e+02, 0.000e+00, 6.000e+00],
         [8.390e+02, 4.960e+02, 8.650e+02, 5.520e+02, 0.000e+00, 7.000e+00],
         [7.230e+02, 4.940e+02, 7.420e+02, 5.300e+02, 0.000e+00, 8.000e+00],
         [1.619e+03, 4.940e+02, 1.671e+03, 5.910e+02, 0.000e+00, 1.000e+01]]),
  (720, 1920, 1, 1, '12/12/out12_0001.jpg'),
  '12/12/out12_0001.jpg'),
 (array([[0.000e+00, 5.170e+02, 4.700e+01, 5.790e+02, 0.000e+00, 1.000e+00],
         [5.740e+02, 4.950e+02, 5.880e+02, 5.520e+02, 0.000e+00, 2.000e+00],
         [5.850e+02, 4.920e+02, 6.220e+02, 5.560e+02, 0.000e+00, 3.000e+00],
  

In [10]:
res, img_info, file_name = annotations[56]

In [11]:
print(res)
print(img_info)
print(file_name)

[[ 36. 463. 104. 566.   0.   7.]
 [461. 449. 509. 569.   0.  10.]]
(720, 1920, 57, 1, '12/12/out12_0057.jpg')
12/12/out12_0057.jpg


In [12]:
img_file = os.path.join(data_dir, name, file_name)

In [13]:
img_file

'/home/administrator/deeplearning/code/Gayhub/detection/MOT/Jerry/ByteTrack/datasets/Jerry/train/12/12/out12_0057.jpg'

In [14]:
img = cv2.imread(img_file)

In [15]:
# cv2.imshow('img',img)
# cv2.waitKey(0)